# Generated by Django 3.2.9 on 2022-01-31 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(max_length=127, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=127, verbose_name='Почта пользователя')),
                ('text', models.TextField(verbose_name='Текст обращения')),
                ('status', models.CharField(choices=[('0', 'opened'), ('1', 'processing'), ('2', 'closed')], default='0', editable=False, max_length=2, verbose_name='Статус обращения')),
                ('time_opened', models.DateTimeField(auto_now_add=True, verbose_name='Время открытия')),
                ('time_closed', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время закрытия')),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
            },
        ),
    ]
