# Generated by Django 3.2.9 on 2021-11-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialunit',
            name='link',
            field=models.TextField(default='http://localhost', verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
