# Generated by Django 3.2.9 on 2021-11-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_financialunit_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialunit',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
