# Generated by Django 3.2.9 on 2021-11-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_financialunit_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialunit',
            old_name='upload',
            new_name='image',
        ),
    ]
