# Generated by Django 3.2.9 on 2021-11-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_upload_financialunit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialunit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='financialunit',
            name='range_str',
        ),
        migrations.RemoveField(
            model_name='financialunit',
            name='short_description',
        ),
        migrations.AddField(
            model_name='financialunit',
            name='bid',
            field=models.CharField(default='от 0% до 1.85% в день', max_length=255, verbose_name='Ставка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialunit',
            name='loan_terms',
            field=models.TextField(default='Пункты условий займа', verbose_name='Условия займа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialunit',
            name='requirements',
            field=models.TextField(default='Пункты требований к заемщику', verbose_name='Требования'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialunit',
            name='sum',
            field=models.CharField(default='50 000', max_length=255, verbose_name='Сумма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialunit',
            name='term',
            field=models.CharField(default='от 5 до 126 дней', max_length=255, verbose_name='Срок'),
            preserve_default=False,
        ),
    ]
