# Generated by Django 3.2.9 on 2021-11-26 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211126_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialunit',
            name='rating',
            field=models.FloatField(default=4.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='financialunit',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 0.0), ('rating__lte', 5.0)), name='foo_rating_range'),
        ),
    ]
