# Generated by Django 3.2.9 on 2021-11-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211126_0225'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='financialunit',
            name='foo_rating_range',
        ),
        migrations.AddConstraint(
            model_name='financialunit',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 0.0), ('rating__lte', 5.0)), name='financialunit_rating_range'),
        ),
    ]
