# Generated by Django 3.2.9 on 2022-01-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211126_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(help_text='Имя настройки, только латинские буквы без', max_length=31, verbose_name='Наименование')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('settings_type', models.CharField(choices=[('int', 'integer'), ('dbl', 'double'), ('str', 'string'), ('lst', 'array (list)')], help_text='Десятичная часть в типе Double разделяется точкой (.) . Массив Array интерпретируется как список строк, каждый элемент которого разделен запятой.', max_length=3, verbose_name='Тип')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
