# Generated by Django 3.2.9 on 2022-01-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(help_text='Имя настройки, только латинские буквы', max_length=31, verbose_name='Наименование'),
        ),
    ]
