# Generated by Django 3.2.9 on 2022-01-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_settings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='settings_type',
            field=models.CharField(choices=[('int', 'integer'), ('dbl', 'double'), ('str', 'string'), ('lst', 'array')], help_text='Десятичная часть в типе Double разделяется точкой (.) . Массив Array интерпретируется как список строк, каждый элемент которого разделен запятой.', max_length=3, verbose_name='Тип'),
        ),
    ]
