# Generated by Django 3.2.9 on 2022-02-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_leadformdata_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadformdata',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма'),
        ),
    ]
