# Generated by Django 3.2.9 on 2022-02-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_leadformdata_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadformdata',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='leadformdata',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='leadformdata',
            name='phone',
            field=models.CharField(blank=True, max_length=31, verbose_name='Телефон'),
        ),
    ]
