# Generated by Django 3.2.9 on 2022-04-12 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220412_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialunit',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.app', verbose_name='Приложение'),
        ),
    ]
