# Generated by Django 3.2.9 on 2022-04-14 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_financialunit_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialunit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='financialunit',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.app', verbose_name='Приложение'),
        ),
        migrations.AlterField(
            model_name='financialunit',
            name='link',
            field=models.TextField(blank=True, default='', verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='financialunit',
            name='loan_terms',
            field=models.TextField(blank=True, null=True, verbose_name='Условия займа'),
        ),
        migrations.AlterField(
            model_name='financialunit',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='financialunit',
            name='term',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Срок'),
        ),
    ]
